version: "3.7"
#* Ini adalah schema version dari Docker Compose yang kita tulis.

services:
#* Ini adalah bagian yang berisi konfigurasi dari service yang kita buat.

  item-app:
  #* service pertama 

    image: 70k0b0d0/item-app:v1
    #* Menggunakan image item-app dari Docker Hub yang sudah kita buat sebelumnya.

    restart: always
    #* Menggunakan restart policy always, yang berarti container akan selalu di-restart jika terjadi error.

    ports:
      - 80:8080
    #* Membuka port 80 dari host dan mengarahkan ke port 8080 dari container.

    depends_on:
      - item-db
    #* Menentukan bahwa service ini bergantung pada service item-db untuk dapat berjalan.

  item-db:
  #* service kedua

    image: mongo:3
    #* Menggunakan image mongo:3 dari Docker Hub.

    restart: always
    #* Menggunakan restart policy always, yang berarti container akan selalu di-restart jika terjadi error.


    volumes:
      - app-db:/data/db
    #* Memakai volume bernama app-db dengan target /data/db di container.

volumes:
  app-db:
  #* Volume bernama app-db