#* Specify the API version for the Secret resource
apiVersion: v1
#* Specify the kind of the Kubernetes resource
kind: Secret
#* Define metadata for the Secret resource
metadata:
  name: mongo-secret
#* Define the data for the Secret resource
stringData:
  mongodb-username: your_username
  mongodb-password: your_password
